### ISSUE TITLE
Implement 4K UHD SDR video 2-pass transcoding

### ISSUE THREAD

**Issue by andreyrikunov** [RoRu/Video-Packager#4]
Le't try to implement simple but real scenario - 4K UHD SDR video 2-pass transcoding.

Source video for development and testing:

[tearsofsteel_4k.mp4](http://profficialsite.origin.mediaservices.windows.net/f2a10623-0848-47cd-9477-6a858ee66c2d/tearsofsteel_4k_60s_24fps.12000kbps.3840x2160.h265-8b.2ch.128kbps.aac.mp4)

**Prerequisites:**

ffmpeg with x265 support

**Hints:**

- In order to make local ffmpeg run faster cut video to first N seconds. 
**Example**:  `ffmpeg -i video_full_duration.mp4 -t 10 -c copy video_10_seconds.mp4`
- Use `preset=ultrafast` to speed up transcoding

**Documentation:**

https://www.ffmpeg.org/ffmpeg-codecs.html#libx265

**Workflow steps:**

1. Analyze video

Use ffprobe to get high level info about an MP4 file (tracks and codec details):

`ffprobe -v quiet -print_format json -show_format -show_streams video_4k.mp4`

or

`ffprobe -v quiet -print_format json -show_format -show_streams video_4k.mp4 > video_4k.mp4.json`

2. Ensure video is 4K UHD SDR

Ensure there is a video track - there is stream with "codec_type": "video"
Width >= 3840
Height >= 2160

3. Transcoding

Parameters:

- input_file
- output_file
- profile=main|main10|mainstillpicture
- preset=ultrafast|superfast|veryfast|faster|fast|medium(default)|slow|slower|veryslow|placebo
- fps (frames per second)

Commands:

2-pass transcoding

Having the following input and analyzed parameters `input_file =video_4k.mp4, output_file =transcoded_video_4k.mp4, profile=main, preset=ultrafast, fps=24`:

```
keyint=fps*2
min-keyin=fps*2

# pass 1
ffmpeg -y -r 24 -i 'video_4k.mp4' -vsync 1 -pix_fmt yuv420p -c:v libx265 -tune zerolatency -profile:v main -x265-params 'input-res=3840x2160:fps=24:level-idc=5.0:high-tier=1:sar=1:no-open-gop=1:keyint=48:min-keyint=48:scenecut=0:no-scenecut=1:colorprim=bt709:bitrate=20000:vbv-maxrate=30000:vbv-bufsize=40000:pass=1' -preset ultrafast -an -map 0:v:0 -an -f mp4 /dev/null 
```

So the template of the command is:

```
ffmpeg -y -r {fps} -i 'video_4k.mp4' -vsync 1 -pix_fmt yuv420p -c:v libx265 -tune zerolatency -profile:v {profile} -x265-params 'input-res=3840x2160:fps={fps}:level-idc=5.0:high-tier=1:sar=1:no-open-gop=1:keyint={fps*2}:min-keyint={fps*2}:scenecut=0:no-scenecut=1:colorprim=bt709:bitrate=20000:vbv-maxrate=30000:vbv-bufsize=40000:pass=1' -preset {preset} -an -map 0:v:0 -an -f mp4 /dev/null 
```

The command above produces the following files: 

```
x265_2pass.log
x265_2pass.log.cutree

```
It is required to preserve these files for pass 2:

```
# pass 2
ffmpeg -y -r 24 -i 'video_4k.mp4' -vsync 1 -pix_fmt yuv420p -c:v libx265 -tune zerolatency -profile:v main -x265-params 'input-res=3840x2160:fps=24:level-idc=5.0:high-tier=1:sar=1:no-open-gop=1:keyint=48:min-keyint=48:scenecut=0:no-scenecut=1:colorprim=bt709:bitrate=20000:vbv-maxrate=30000:vbv-bufsize=40000:pass=2' -preset ultrafast -an -map 0:v:0 -an -f mp4 transcoded_video_4k.mp4
```

4. Expecting the `transcoded_video_4k.mp4` have been created

**Comment by RoRu** [comment]
@andreyrikunov 
> profile=main|main10|mainstillpicture

This option doesn't seem to work for me. Also, there's no mention of it in ffmpeg documentation 
 (but it is used in examples in ffmpeg-all docs) and `ffmpeg` fails when I try to run it with `-profile:v main`

**Comment by andreyrikunov** [comment]
These options are in x265 help:

```
$ x265 --help | grep main
x265 [info]: HEVC encoder version 2.9
x265 [info]: build info [Mac OS X][clang 10.0.0][64 bit] 8bit+10bit+12bit
-P/--profile <string>            Enforce an encode profile: main, main10, mainstillpicture
```

**Comment by andreyrikunov** [comment]
> ffmpeg fails when I try to run it with -profile:v 

most probably your ffmpeg doesn't built with libx265 support

please run `ffmpeg` without parameters in look for `--enable-libx265` in configuration options

**Comment by RoRu** [comment]
It actually does work as a x265 option, but not ffmpeg's like in your original post here:
>ffmpeg -y -r 24 -i 'video_4k.mp4' -vsync 1 -pix_fmt yuv420p -c:v libx265 -tune zerolatency -**profile:v main** -x265-params 'input-res...
